# User Config
# ===========
# fill/change these fields to match your own.

# Identity
# --------

title:       Smallhand's notes
description: some of my favourite thoughts

logo:  "/assets/img/logo.png"
cover: "/assets/img/cover.png"

baseurl: ""
url:     "https://atkpwn.github.io"

owner:  Attakorn
rights: CC-BY


# Social & Sharing
# ----------------

google:
  analytics:    UA-184084541-1
  verification: fHiOBNsadQ4SzAq_DXYyP8isadPlu3jgT_tfEj_zdVA

facebook:
  username: atkpwn
  app_id:   1511165182424657

twitter:
  username:
  large_img: never

disqus:
  username: atkpwn

# Content Format
# --------------

timezone: Europe/Berlin
paginate: 10
mathjax:  true


# Engine Config
# =============
# you shouldn't change this unless you really know what you're doing.

collections:
  projects:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

permalink: date
paginate_path: "/posts/page:num"

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md

plugins:
  - jekyll-sitemap
  - jekyll-paginate

empty_array: []
